services:
  easy:
    build: ./challenges/easy_metadata_challenge
    image: ctf-easy-metadata
    container_name: ctf-easy-metadata
    ports:
      - "8080:8080"
    restart: unless-stopped

  medium:
    build: ./challenges/medium_web_challenge
    image: ctf-medium-web
    container_name: ctf-medium-web
    ports:
      - "5000:5000"
    restart: unless-stopped

  hard:
    build: ./challenges/hard_ssh_suid_challenge
    image: hard-ssh-suid
    container_name: ctf-hard-ssh-suid
    ports:
      - "2222:22"
    restart: unless-stopped
